config/routes.rb
EatitWeb::Application.routes.draw do
  root 'index#index'

  get  'auth/:provider/callback' => 'users#auth_fb'
  get  'sign_failure'            => 'users#failure'
  post 'sign_upping'             => 'users#sign_upping'
  get  'sign_out'                => 'users#sign_out'
  get  'user/account'            => 'users#account'

  resources :restaurants do
    collection do
      get 'search'
    end
  end

  resources :tasks do
    collection do
      get  'before/:offset' => 'tasks#before',  as: 'before',     offset: /[0-9]*/
      post 'fetch'          => 'tasks#fetch',   as: 'fetch'
      post 'finish/:id'     => 'tasks#finish',  as: 'finish'
      post 'repeat/:id'     => 'tasks#repeat',  as: 'repeat'
    end
  end

  get '/:fb_username' => 'users#index', as: 'user_page'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :score
  has_many :tasks
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user_tasks = Task.joins(:user).where({users: {username: params[:fb_username]}, status: 'Y'})
    @user_info = User.where({username: params[:fb_username]}).first
    # render text: @user_tasks.to_json
  end

	def sign_in
    redirect_to dashboard_root_path if session.has_key?(:UserInfo)
  end

  def auth_fb
    auth_hash = request.env['omniauth.auth']
    if auth_hash
      authUser = User.where(:fb_id=> auth_hash['uid']).first
      if authUser
        authUser.update_attributes(:token => auth_hash['credentials']['token'])
      else
        authUser = User.new({
                              username: auth_hash[:extra][:raw_info][:username],
                              name: auth_hash['info']['name'],
                              email: auth_hash['info']['email'],
                              fb_id: auth_hash['uid'],
                              token: auth_hash['credentials']['token']
                              })
        authUser.save
      end
      session[:UserInfo] = { id: authUser.id, fb_id: authUser.fb_id, name: authUser.name, username: authUser.username}
      redirect_to root_path
    else
      redirect_to sign_failure_path
    end
  end

  def account
    @user = User.find(session[:UserInfo][:id])
  end

  def sign_upping
    @user = User.find(params[:user][:id]).update_attributes(user_params)
    authUser = User.find(params[:user][:id])
    session[:UserInfo] = { :id => authUser.id, :fb_id => authUser.fb_id, :name => authUser.name}
    redirect_to root_path
  end

  def sign_out
    session.delete(:UserInfo)
    reset_session
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.haml
#account
  %h1.page-header= t("account")
  = form_for @user, :url=> sign_upping_path(@user), method: "post", :html => {:class=> 'form-horizontal col-md-12', :role=> 'form'} do |f|
    = f.text_field :id, type: "hidden"
    .form-group.float-label-control
      = f.label :name, t('user.name'), for: ''
      = f.text_field :name, :class=>'form-control'

    .form-group.float-label-control
      = f.label :email, t('user.email'), for: ''
      = f.email_field :email, :class=>'form-control'

    .form-group.text-center
      = f.submit t('update'), :class=> 'btn btn-lg btn-success btn-block'

app/views/users/index.html.haml
.container
  .page-header.text-center
    %img.img-circle{:src => "https://graph.facebook.com/#{@user_info.fb_id}/picture?type=large", :alt => @user_info.username, width: 120}
    %h2#timeline
      = @user_info.name
  %ul.timeline
    - @user_tasks.each do |task|
      %li{class: cycle('', 'timeline-inverted')}
        .timeline-badge.primary
          %a
            %i.glyphicon.glyphicon-record{:id => "", :rel => "tooltip", :title => "11 hours ago via Twitter"}

        .timeline-panel
          -# .triangle
          %i.fa.fa-star.fa-3x
          .timeline-heading
            -# %img.img-responsive{:src => "http://lorempixel.com/1600/500/sports/2"}/
          .timeline-body
            %p= task.name
          .timeline-footer
            %a
              %i.glyphicon.glyphicon-thumbs-up
            -# %a
            -#   %i.glyphicon.glyphicon-share
            -# %a.pull-right Continuar Lendo
            .pull-right
              .fb-like{"data-action" => "like", "data-href" => task_path(task), "data-layout" => "button_count", "data-share" => "true", "data-show-faces" => "true"}
    %li.clearfix{:style => "float: none;"}

app/views/users/sign_in.html.haml
.container
  .row.vertical-offset-100
    .h1.text-center.page-header
      %a{:href => root_path}
        %i.fa.fa-cutlery
        %span.light Eat it
    .col-md-4.col-md-offset-4
      .panel.panel-default
        .panel-heading
          %h3.panel-title= t('page.sign_in.header')
        .panel-body
          %a.btn.btn-lg.btn-primary.btn-block{:href => "/auth/facebook"}
            %i.fa.fa-1x.fa-facebook
              = t('page.sign_in.sign_in_text')

app/views/users/sign_up.html.haml
%div#account.container
    %h1= t("user.sign_up")
    %hr/
    = form_for @user, :url=> sign_upping_path(@user), method: "post", :html => {:class=> 'form-horizontal', :role=> 'form'} do |f|
        = f.text_field :id, type: "hidden"
        %div.form-group.row
            = f.label :classes, t('sign_up.classes'), :class=>'col-md-3 control-label'
            %div.col-md-7
                = f.select(:classes, [[t('study.master'), "master"], [t('study.university'), "university"]], {}, {:class=>'form-control'})

        %div.form-group.row
            = f.label :name, t('sign_up.name'), :class=>'col-md-3 control-label'
            %div.col-md-7
                = f.text_field :name, :class=>'form-control'
            %p.text-warning= t('user.note-name')

        %div.form-group.row
            = f.label :email, :class=>'col-md-3 control-label'
            %div.col-md-7
                = f.email_field :email, :class=>'form-control'
            %p.text-warning= t('user.note-email')

        %div.form-group.row
            = f.label :phone, t('sign_up.phone'), :class=>'col-md-3 control-label'
            %div.col-md-7
                = f.number_field :phone, :class=>'form-control'
            %p.text-warning= t('user.note-phone')
        %div.form-group
            %div.col-md-offset-3.col-md-10
                = f.submit t("user.sign_up"), :class=> 'btn btn-success col-md-8'